---
title: "Paper Figures and Tables"
author: "MM Thomas"
date: "2024-02-18"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
source(here::here("Helper_Functions/data-readin.R"))
library(ggplot2)
library(tidyverse)
library(CARBayes)
library(coda)
library(viridis)
library(cowplot)
library(tmap)

# Poverty Data (DP03_119PE)Percent!!PERCENTAGE OF FAMILIES AND PEOPLE WHOSE INCOME IN THE PAST 12 MONTHS IS BELOW THE POVERTY LEVEL!!All families
# Vacant housing units (DP04_0003PE)
# Percent!!EMPLOYMENT STATUS!!Civilian labor force!!Unemployment Rate (DP03_0009PE)
ga_map_data <- data_readin(acs_vars = "DP03_0119PE,DP04_0003PE,DP03_0009PE,DP05_0065PE", acs_yr = 2020, mort_year = 2020)


ga_map_data %>% summarise(across(matches("unemploy"), list(mean = mean, max = max))) 

glimpse(ga_map_data)
```


### Distance Metrics Added

### Map Components

```{r disttoroad}

ga_map_data_short <- ga_map_data %>% 
  filter(!is.na(dist_to_usroad))

# The following two counties were removed from the adjacency matrix.
# ga_map_data %>% 
#   st_drop_geometry() %>% 
#   mutate(county_id = row_number()) %>% 
#   dplyr::select(county_id, COUNTY, dist_to_usroad) %>% 
#   filter(is.na(dist_to_usroad))
# county_id   COUNTY dist_to_usroad
# 1       158 Columbia             NA
# 2       159   Echols             NA 

```

```{r weightmatrixdist}
# Bayes---------------------------------------------------

ga_map_nb_short <- spdep::poly2nb(ga_map_data_short, queen = F)

W_mt_short <- spdep::nb2mat(ga_map_nb_short, style = "B")

# Print the smoothed map
# ps <- ggplot(ga_map_data) + 
#   geom_sf(aes(fill = incidence * 1000)) +
#   labs(title = "Unsmoothed\n Mortality Rates 19")

# plot(ga_map_nb)

# print(ps)

# ga_map_data %>% arrange(desc(incidence)) %>% slice(1:20) %>% mutate(od_rank = row_number())

```


```{r}
ga_map_data_short %>% 
  ggplot(aes(x = rucc_code13_5, y = incidence)) +
  geom_boxplot() +
  theme_bw()

ga_map_data_short %>% 
  ggplot(aes(x = rucc_code13_5)) +
  geom_bar() +
  theme_bw()
```


## Maps

### RUCC Codes/Covariates

```{r}

ga_map_data %>% 
  rename(pct_minority_std = pct_black_std) %>% 
  tm_shape() +
    tm_polygons(c("incidence", "pct_poverty_std", "vacancy_rate_std", "unemployment_rate_out_std", 
                  "dist_to_usroad_std", "dist_to_treatment_std", "pct_minority_std",
                  "rucc_code13_5"),
                
                #, 
                # fill.scale = list(tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_discrete())
                  # list(tm_scale_categorical(),
                  #                 tm_scale_ordinal(),
                  #                 tm_scale_intervals(),
                  #                 tm_scale_continuous(),
                  #                 tm_scale_continuous_log(),
                  #                 tm_scale_discrete())
                #,
                # fill.legend = tm_legend(title = "", position = tm_pos_in("left", "top"))
                ) +
    tm_layout(panel.labels = c("Raw Incidence", "Poverty", "Vacancy Rate", "Unemployment Rate", "Dist to USRoad", "Dist to Treatment", "Percent Minority",
                               "Rural/Urban"), 
              inner.margins = c(0.05, 0.4, 0.1, 0.05),
              legend.text.size = 1.0,
              fontfamily = "serif")

 #%>% 
  # rename_with(~ paste0(.x, "_std", recycle0 = T), c("pct_poverty", "vacancy_rate", "unemployment_rate"))

```

### Specific Maps for Power Point

```{r}


ga_map_data %>% 
  rename(pct_minority_std = pct_black_std) %>% 
  tm_shape() +
    tm_polygons(c("vacancy_rate_std", "unemployment_rate_out_std", 
                  "dist_to_usroad_std", "dist_to_treatment_std",
                  "pct_minority_std","rucc_code13_5"),
                
                #, 
                # fill.scale = list(tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_continuous(),
                #                   tm_scale_discrete())
                  # list(tm_scale_categorical(),
                  #                 tm_scale_ordinal(),
                  #                 tm_scale_intervals(),
                  #                 tm_scale_continuous(),
                  #                 tm_scale_continuous_log(),
                  #                 tm_scale_discrete())
                #,
                # fill.legend = tm_legend(title = "", position = tm_pos_in("left", "top"))
                ) +
    tm_layout(panel.labels = c("Vacancy Rate", "Unemployment Rate", "Dist to USRoad", "Dist to Treatment", "Percent Minority",
                               "Rural/Urban"), 
              panel.label.size = 1.4,
              legend.title.color = "white",
              inner.margins = c(0.05, 0.4, 0.1, 0.05),
              legend.text.size = 1.4,
              fontfamily = "serif")

ga_map_data %>% 
  st_drop_geometry() %>% 
  count(rucc_code13_5) %>% 
  mutate(pct = format(round(n / sum(n) ,4), nsmall = 4))

```


## Correlations

```{r maps}
vars_ <- c(sort(c("dist_to_usroad_std", "dist_to_treatment_std", "pct_poverty_std","pct_black_std", "vacancy_rate_std", "unemployment_rate_out_std")), "incidence")

print("Pearson Correlation==================")
Hmisc::rcorr(as.matrix(st_drop_geometry(ga_map_data_short[,vars_])))[c(1,3)]

print("Spearman Correlation=================")
Hmisc::rcorr(as.matrix(st_drop_geometry(ga_map_data_short[,vars_])),type = 'spearman')[c(1,3)]

```

## Bivariate Scatterplots
```{r}


lookup_varname <- function(x){
  lookup <- c(`dist_to_treatment_std` = "Distance to Treatment",
`dist_to_usroad_std` = "Distance to US Road",
`pct_black_std` = "Percent Population Minority",
`pct_poverty_std` = "Percent Under Poverty Line",
`unemployment_rate_out_std` = "Unemployment Rate",
`vacancy_rate_std` = "Vacancy Rate",
`incidence` = "Opioid Mortality Rate")

  factor(unname(lookup[x]),
                levels = c("Distance to Treatment", "Distance to US Road", "Percent Population Minority",
                  "Percent Under Poverty Line", "Unemployment Rate", "Vacancy Rate", 
                  "Opioid Mortality Rate"))
  
}

ga_map_data_short %>% st_drop_geometry() %>%
  mutate(Incidence = incidence * 1000) %>% 
  pivot_longer(cols = c(pct_poverty_std, vacancy_rate_std, unemployment_rate_out_std,
                        dist_to_usroad_std, dist_to_treatment_std,
                        pct_black_std)) %>%
  mutate(name = lookup_varname(name)) %>% 
  ggplot(aes(x = value, y = Incidence)) +
  geom_point(alpha = 1 / 3) +
  geom_smooth(colour = "black", method  = "lm") +
  theme_bw() +
  labs(x = "Percent", y = "Opioid Mortality Rate",
       title = "Plot of Indicator Association with Incidence",
       subtitle = "for GA Counties") +
  theme(guide = NULL, text = element_text(family = "serif")) +
  facet_wrap("name",ncol = 3)

```


## Scatterplot Matrix


You can also embed plots, for example:

```{r pressure, echo=FALSE}
ga_map_data_short %>% st_drop_geometry() %>% 
  mutate(Incidence = incidence * 1000) %>% 
  pivot_longer(cols = c(pct_poverty_std, vacancy_rate_std, unemployment_rate_out_std, dist_to_usroad_std, dist_to_treatment_std, pct_black_std)) %>% 
  mutate(name = lookup_varname(name)) %>% 
  ggplot(aes(x = value, y = Incidence)) +
  geom_point(alpha = 1 / 3) +
  geom_smooth(colour = "black", method = "lm") +
  theme_bw() +
  labs(x = "Standardized Value", y = "Opioid Mortality Rate per 1,000", 
       title = "Plot of Indicator Association with Incidence",
       subtitle = "for GA Counties") +
  theme(guide = NULL, text = element_text(family = "serif")) +
  facet_grid(rucc_code13_5~name, space = "free")

```

## Regressions

```{r}

post_prob <- function(var_index, model, val_ = 0, loop = F){
  if(loop == T){
    for(i in 1:ncol(model$samples$beta)){
      print(paste0(row.names(model$summary.results)[i], " Post Prob:"))
      prob_ <- sum(model$samples$beta[,i] > val_) / length(model$samples$beta[,i])
      print(prob_)
      }
  } else{
        print(paste0(row.names(model$summary.results)[var_index], " Post Prob:"))
      prob_ <- sum(model$samples$beta[,var_index] > val_) / length(model$samples$beta[,var_index])
      print(prob_)
    }
}

post_prob_lt <- function(var_index, model, val_ = 0, loop = F){
  if(loop == T){
    for(i in 1:ncol(model$samples$beta)){
      print(paste0(row.names(model$summary.results)[i], " Post Prob:"))
      prob_ <- sum(model$samples$beta[,i] < val_) / length(model$samples$beta[,i])
      print(prob_)
      }
  } else{
        print(paste0(row.names(model$summary.results)[var_index], " Post Prob:"))
      prob_ <- sum(model$samples$beta[,var_index] < val_) / length(model$samples$beta[,var_index])
      print(prob_)
    }
}

```



# Full Model

```{r bayesdist}

form <- "mortality ~ vacancy_rate_std + dist_to_treatment_std + pct_poverty_std + unemployment_rate_out_std + pct_black_std + offset(log(population))"
model.spatial.full <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = 1)

# model.spatial.chain2 <- S.CARleroux(as.formula(form), family = "poisson",
#                              data = ga_map_data_short,
#                              W = W_mt_short, burnin = 2000, n.sample = 1e6, 
#                              thin = 10, rho = .8)

# model.spatial.chain2_small <- S.CARleroux(as.formula(form), family = "poisson",
#                              data = ga_map_data_short,
#                              W = W_mt_short, burnin = 2000, n.sample = 1e5, 
#                              thin = 10, rho = .8)

# Need to add comparison chain
# plot(mcmc.list(model.spatial$samples$beta, model.spatial.chain2$samples$beta)[,-1])

# model <- glm(as.formula(form), family = "poisson",
#             data = ga_map_data)

print(summary(model.spatial.full))
print(model.spatial.full)
# print(model.spatial.chain2_small)

post_prob(2, model.spatial.full, 0, loop = T)
post_prob_lt(2, model.spatial.full, 0, loop = T)
exp(model.spatial.full$summary.results[,1:3] )

```

# Poverty in Core

```{r bayesdist_povruc}

form <- "mortality ~ pct_poverty_std * relevel(rucc_code13_5, ref = 'mi_non') + offset(log(population))"
model.spatial.povrucc <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = .8)

print(summary(model.spatial.povrucc))
print(model.spatial.povrucc)
post_prob(2, model.spatial.povrucc, 0, loop = T)
exp(model.spatial.povrucc$summary.results[,1:3])

```

# Vacancy in SM

```{r bayesdist_vacruc}

form <- "mortality ~ vacancy_rate_std * rucc_code13_5 + offset(log(population))"
model.spatial.vacruc <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = .8)

print(summary(model.spatial.vacruc))
print(model.spatial.vacruc)
post_prob(2, model.spatial.vacruc, 0, loop = T)
exp(model.spatial.vacruc$summary.results[,1:3])

```

# Treatment in SM

```{r bayesdist_treatruc}

form <- "mortality ~ dist_to_treatment_std * rucc_code13_5 + offset(log(population))"
model.spatial.treatruc <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = .8)

print(summary(model.spatial.treatruc))
print(model.spatial.treatruc)
post_prob(2, model.spatial.treatruc, 0, loop = T)
exp(model.spatial.treatruc$summary.results[,1:3])

```


```{r bayesdist_heurmodel}

form <- "mortality ~ unemployment_rate_out_std + dist_to_treatment_std + vacancy_rate * rucc_code13_5 + offset(log(population))"
model.spatial.full.vacrucc <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = .8)

print(summary(model.spatial.full.vacrucc))
print(model.spatial.full.vacrucc)
post_prob(2, model.spatial.full.vacrucc, 0, loop = T)
# exp(model.spatial$summary.results[,1:3])

```

```{r}

form <- "mortality ~ dist_to_treatment_std + vacancy_rate + offset(log(population))"
model.spatial.pars.distvac <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = .8)

print(summary(model.spatial.pars.distvac))
print(model.spatial.pars.distvac)
post_prob(2, model.spatial.pars.distvac, 0, loop = T)
# exp(model.spatial$summary.results[,1:3])

```

# With Self

```{r bayesfullself}

W_mt_short_self <- W_mt_short
diag(W_mt_short_self) <- 1

form <- "mortality ~ vacancy_rate_std + dist_to_treatment_std + pct_poverty_std + unemployment_rate_out_std + pct_black_std + offset(log(population))"
model.spatial.full.self <- S.CARleroux(as.formula(form), family = "poisson",
                             data = ga_map_data_short,
                             W = W_mt_short_self, burnin = 2000, n.sample = 1e6,
                             thin = 10, rho = 1)

# model.spatial.chain2 <- S.CARleroux(as.formula(form), family = "poisson",
#                              data = ga_map_data_short,
#                              W = W_mt_short, burnin = 2000, n.sample = 1e6, 
#                              thin = 10, rho = .8)

# model.spatial.chain2_small <- S.CARleroux(as.formula(form), family = "poisson",
#                              data = ga_map_data_short,
#                              W = W_mt_short, burnin = 2000, n.sample = 1e5, 
#                              thin = 10, rho = .8)

# Need to add comparison chain
# plot(mcmc.list(model.spatial$samples$beta, model.spatial.chain2$samples$beta)[,-1])

# model <- glm(as.formula(form), family = "poisson",
#             data = ga_map_data)

print(summary(model.spatial.full))
print(model.spatial.full.self)
# print(model.spatial.chain2_small)

post_prob(2, model.spatial.full, 0, loop = T)
exp(model.spatial.full$summary.results[,1:3] )

```


## Regression Map


```{r}

x <- ga_map_data_short$incidence
W <- W_mt_short_self

# t(matrix(rep(1,157))) %*% W

adjacency_smoothed <- as.vector(t(matrix(x)) %*% W / rowSums(W))

ga_map_data_short <- ga_map_data_short %>%
  mutate(incidence_adj = adjacency_smoothed) 

```


```{r}

ga_map_data_short_map <- ga_map_data_short %>% 
  mutate(incidence_na = ifelse(incidence == 0, NA_real_, incidence),
         mortality_smooth = model.spatial.full$fitted.values,
         incidence_smooth = mortality_smooth / population)

plot(ga_map_data_short_map$incidence, ga_map_data_short_map$incidence_smooth)


bbox_new <- st_bbox(ga_map_data_short_map) # current bounding box

xrange <- bbox_new$xmax - bbox_new$xmin # range of x values
yrange <- bbox_new$ymax - bbox_new$ymin # range of y values

# bbox_new[1] <- bbox_new[1] - (0.25 * xrange) # xmin - left
 bbox_new[3] <- bbox_new[3] + (0.15 * xrange) # xmax - right
# bbox_new[2] <- bbox_new[2] - (0.25 * yrange) # ymin - bottom
bbox_new[4] <- bbox_new[4] + (0.1 * yrange) # ymax - top

ga_map_data_short_map %>% 
  mutate(across(c(incidence_na, incidence_adj, incidence_smooth), .fns = ~.x * 1000)) %>% 
  rename(`Incidence Raw` = incidence_na, `Incidence Adj` = incidence_adj, `Incidence Bayes` = incidence_smooth) %>% 
  tm_shape(bbox = bbox_new) +
  tm_polygons(col = c("Incidence Raw", "Incidence Adj", "Incidence Bayes"), 
              midpoint = 0,
              style  = "cont",
              pal = viridis(10)) +
  tm_shape(ga_map_data) +
  tm_borders() +
  tm_layout(legend.position = c("right", "top"),
            legend.text.size = .7,
            fontfamily = "serif")


ga_map_data_short_map %>% 
  st_drop_geometry() %>% 
  rename(`Incidence Raw` = incidence, `Incidence Adj` = incidence_adj, `Incidence Bayes` = incidence_smooth) %>% 
  pivot_longer(c(`Incidence Raw`, `Incidence Adj`, `Incidence Bayes`), names_to = "Method", values_to = "Incidence Estimate") %>% 
  mutate(Method = factor(Method, levels = c("Incidence Adj", "Incidence Raw","Incidence Bayes")),
         `Incidence Estimate` = `Incidence Estimate` * 1000) %>% 
  ggplot(aes(x = Method, y = `Incidence Estimate`, group = NAME)) +
  geom_line(alpha = 1 / 5) +
  geom_point(alpha = 1/ 10) +
  theme_bw() +
  theme(text = element_text(family="serif")) 

var.test(ga_map_data_short_map$incidence,ga_map_data_short_map$incidence_adj)

var.test(ga_map_data_short_map$incidence,ga_map_data_short_map$incidence_smooth)

sd(ga_map_data_short_map$incidence)
sd(ga_map_data_short_map$incidence_smooth)
sd(ga_map_data_short_map$incidence_adj)

```

